@SimpleAuth_HostAddress = http://localhost:5120
@JwtToken = Bearer CfDJ8GAEj8ahT6pIk28eIci2JU1Id88ZDqqae1MCYsEGjecw12AzILTRbTsAlx9YZOhBJ6Ein8FWlTz4gJDx9qY0E84Uv93xkbHA-S30tvg-8848QJ_IatQYpnGjFG4djP_AfYo3tSbWaHqUP9R-qqGF2-FN98p3KwT1G620wfmaSnvwrPQz2_EM09Rh04MgOPW_94aQ-U9QXOcF9z2XhVIyEDjlw3vduj08XrfWYEzLNk246JFgbHl0-43-dJ1M8RjyiiubRAqetpwqhUBOTAhf0oau_nS-BB_zJeq6mjMAz7YmzoAlxZ7OR9BwUl5qPqT2xYe6wv-JwK87xcik5ZmNU7Tb-CuEN_kXzOl-tOSK1J-2drCcv-yMhH4b5K1gHc9aPPBYdJHiyaBSY4fZgPGUB_13XSgxYjMJsZNRMMEbE-gEZYmo7DxNk-ZqBupoiDeVX0B43a0rSy3bo9FIBen2knsYN_b2BSkLFiq3UQKji_nFwM_Kl6wy9VGLiSqZ1t-7icPY4Gz65y91db-4gvWTrki05MXOBZooT4iqAICSj6GGRCfGV-2m5O9fIiVscIMsXlB_PxPK2YyEMpZCFy0bje0mec_k9ptr4FsWRxODBur2OTfv3eT87mguVluAZkdNCYseFnpXszgmlBKUQuwMqU5SBM-0SRtViV5A4OBvhsk-JhJm40F_ja3j7e-DWuvx5g

### Register

POST {{SimpleAuth_HostAddress}}/register
Accept: */*
Content-Type: application/json

{
  "email": "teste@email.com",
  "password": "P@ssw0rd"
}

### Login

POST {{SimpleAuth_HostAddress}}/login
Accept: */*
Content-Type: application/json

{
  "email": "teste@email.com",
  "password": "P@ssw0rd"
}

### Auth Test

GET {{SimpleAuth_HostAddress}}/auth/health
Authorization: {{JwtToken}}
